VISH.Samples = (function(V,undefined){

	//Hotspots
	var hotspot_samples = {"VEVersion":"0.9.4","type":"presentation","vishMetadata":{"name":"ViSH Editor Development","draft":"true"},"slides":[{"id":"article1","type":"flashcard","background":"url(\"https://vishub.org/pictures/20206.png\")","pois":[],"slides":[]}]};

	//Basic VE Presentation (only standard slides)
	var basic_samples = {
		//LO metadata
		"id":"1",
		"title":"The Iberian Lynx",
		"description":"The Iberian Lynx.\nAmazing presentation with images, videos and objects, generated by ViSH Editor.",
		"author":"ViSH Editor Team",
		"language":"en",
		"avatar":"http://vishub.org/assets/logos/original/excursion-10.png",
		"tags":["Doñana","Lynx"],
		//Pedagogical metadata
		"age_range":"4 - 20",
		"subject":["Biology"],
		"educational_objectives":"Know about Iberian Lynx",
		"adquired_competencies":"Pupils will be smarter",
		//ViSH Editor metadata
		"VEVersion":"0.2",
		"type":"presentation",
		"theme":"theme1",
		"animation": "animation1",
		
		"slides":[
			{
				"id":"article1",
				"type":"standard",
				"template":"t1",
				"elements":[
					{
						"id":"article1_zone1",
						"type":"image",
						"areaid":"left",
						"body":"http://vishub.org/pictures/312.jpg",
						"style":"position: relative; width:117.0886075949367%; height:109.47368421052632%; top:-4.7368421052631575%; left:-2.5316455696202533%;"
					},
					{
						"id":"article1_zone2",
						"type":"text",
						"areaid":"header",
						"body":"<div class=\"initTextDiv vish-parent-font4\" style=\"text-align: right; font-weight: normal; \"><span class=\"vish-font4 vish-fonthelvetica\" style=\"color:undefined;undefined;\"><b><i><br></i></b></span></div><div class=\"initTextDiv vish-parent-font4\" style=\"text-align: right;\"><span class=\"vish-font4 vish-fonthelvetica\" style=\"color:undefined;undefined;\"><b><i><br></i></b></span></div><div class=\"initTextDiv vish-parent-font4 vish-parent-fontundefined\" style=\"text-align: right;\"><span class=\"vish-font4 vish-fonthelvetica\" style=\"color:undefined;undefined;\"><i>by <b><span class=\"vish-fontundefined vish-fontHelvetica\" style=\"color:#cb6120;undefined;\">Vish</span> Editor</b> Team<b>&nbsp;</b></i></span></div>"
					},{
						"id":"article1_zone3",
						"areaid":"subheader"
					}
				]
			},{
				"id":"article2",
				"type":"standard",
				"template":"t8",
				"elements":[
					{
						"id":"article2_zone1",
						"type":"text",
						"areaid":"header",
						"body":"<div class=\"initTextDiv vish-parent-font6 vish-parent-fontundefined\" style=\"font-weight: normal; \"><span class=\"vish-font6 vish-fontHelvetica\" style=\"color:#db9600;font-weight: bold;  ;\">Iberian</span><span class=\"vish-font6 vish-fontHelvetica\" style=\"color:undefined;font-weight: bold; ;\"> Lynx &nbsp; &nbsp; &nbsp;</span><span class=\"vish-fontundefined vish-fontHelvetica\" style=\"color:#5ea099;undefined;\">Description and habitat</span></div>"
					},{
						"id":"article2_zone2",
						"type":"image",
						"areaid":"left",
						"body":"http://vishub.org/pictures/73.jpeg",
						"style":"position: relative; width:130.4%; height:106.6%; top:0.5%; left:-25.2%;"
					},{
						"id":"article2_zone3",
						"type":"text",
						"areaid":"center",
						"body":"In most respects, the Iberian Lynx resembles other species of lynx, with a short tail,tufted ears and a ruff of fur beneath the chin. ...<div class=\"vish-parent-font7\" style=\"font-weight: normal; \"><span class=\"vish-font7 vish-fontHelvetica\" style=\"color:undefined;undefined;\"></span></div>"
					},{
						"id":"article2_zone4",
						"type":"image",
						"areaid":"right",
						"body":"http://vishub.org/pictures/313.png",
						"style":"position: relative; width:119.5%; height:88.6%; top:3.4%; left:-2.6%;"
					}
				]
			},{
				"id":"article3",
				"type":"standard",
				"template":"t3",
				"elements":[
					{
						"id":"article3_zone1",
						"type":"text",
						"areaid":"header",
						"body":"<span class=\"vish-font6 vish-fontHelvetica\" style=\"color: rgb(219, 150, 0); font-weight: normal; \">Iberian</span><span class=\"vish-font6 vish-fontHelvetica\" style=\"color:undefined;font-weight: bold; ;\">&nbsp;</span><span class=\"vish-font6 vish-fontHelvetica\" style=\"color:undefined;font-weight: bold; ;\">Lynx</span><div class=\"vish-parent-font4\"><span class=\"vish-font4 vish-fontHelvetica\" style=\"color:undefined;undefined;\"></span></div>"
					},{
						"id":"article3_zone2",
						"type":"object",
						"areaid":"left",
						"body":"<iframe src=\"http://www.youtube.com/embed/8t29CZcGAbs?wmode=opaque\" frameborder=\"0\" id=\"resizableunicID9\" class=\"t3_object\" wmode=\"opaque\"></iframe>","style":"position: relative; width:85.81661891117479%; height:100%; top:0.22321428571428573%; left:6.446991404011461%;"
					}
				]
			},
			{
				"id":"article4",
				"type":"standard",
				"template":"t6",
				"elements":[
					{
						"id":"article4_zone1",
						"type":"text",
						"areaid":"header",
						"body":"<div class=\"initTextDiv vish-parent-font6\" style=\"font-weight: normal; \"><span class=\"vish-font6 vish-fontHelvetica\" style=\"color:#db9600;font-weight: bold;  ;\">Iberian</span><span class=\"vish-font6 vish-fontHelvetica\" style=\"color:undefined;font-weight: bold; ;\">&nbsp;Lynx</span><br></div>"
					},{
						"id":"article4_zone2",
						"type":"image",
						"areaid":"left",
						"body":"http://vishub.org/pictures/314.jpeg",
						"style":"position: relative; width:373.6111111111111%; height:217.9%; top:-34.97%; left:-42.13%;"
					},{
						"id":"article4_zone3",
						"type":"image",
						"areaid":"center",
						"body":"http://vishub.org/pictures/314.jpeg",
						"style":"position: relative; width:373.1%; height:217.7%; top:-46.9%; left:-199.1%;"
					},{
						"id":"article4_zone4",
						"type":"text",
						"areaid":"right",
						"body":"<div class=\"vish-parent-font4 vish-parent-fontundefined\" style=\"text-align: center; font-weight: normal; \"><span class=\"vish-font4 vish-fontHelvetica\" style=\"color:undefined;undefined;\">During the mating season the female leaves her territory...</span><span class=\"vish-fontundefined vish-fontHelvetica\" style=\"color:undefined;undefined;\"></span></div>"
					}
				]
			},{
				"id":"article5",
				"type":"standard",
				"template":"t10",
				"elements":[
					{
						"id":"article5_zone1",
						"type":"object",
						"areaid":"center",
						"body":"<iframe src=\"http://en.wikipedia.org/wiki/Do%C3%B1ana_National_Park?wmode=transparent\" id=\"resizableunicID15\" class=\"t10_object\" wmode=\"opaque\"></iframe>",
						"style":"position: relative; width:100%; height:100%; top:0%; left:0%;"
					}
				]
			},{
				"id":"article6",
				"type":"standard",
				"template":"t12",
				"elements":[
					{
						"id":"article6_zone1",
						"areaid":"left1"
					},{
						"id":"article6_zone2",
						"areaid":"right1"
					},{
						"id":"article6_zone3",
						"areaid":"left2"
					},{	
						"id":"article6_zone4",
						"type":"image",
						"areaid":"right2",
						"body":"http://vishub.org/pictures/312.jpg",
						"style":"position: relative; width:114.6%; height:113.8%; top:0%; left:0%;"
					}
				]
			}
		]
	};

	return {
		hotspot_samples		: hotspot_samples,
		basic_samples		: basic_samples
	};

})(VISH);